name: Update Text File

on:
  push:
    branches:
      - main

jobs:
  update-text-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Update the text file
      run: |
        echo "Updated on $(date)" >> ./Demo/F1

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add ./Demo/F1
        git commit -m "Auto-update text file with timestamp"
        git push origin main
