name: Print File Content

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  print-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Print the file contents
      run: |
        cat path/to/your-file.txt
